"""add profile_image and additional_images

Revision ID: 9a217c15c0e9
Revises: fa9cb4b1c057
Create Date: 2026-02-12 09:57:13.487637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a217c15c0e9'
down_revision = 'fa9cb4b1c057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_images', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('additional_images')

    # ### end Alembic commands ###
